#!/bin/bash
# EXA RESEARCH AUTOMATION
# Runs unique Exa searches and documents findings
# Call this every 15 minutes via cron or loop

set -e

RESEARCH_DIR="/home/ubuntu/clawd/memory/research"
mkdir -p $RESEARCH_DIR

TIMESTAMP=$(date -u '+%Y%m%d-%H%M')
DATE=$(date -u '+%Y-%m-%d')
HOUR=$(date -u '+%H')

# Determine research topic based on hour (cycles every 5 hours)
# Hour 0,5,10,15,20: Competitors
# Hour 1,6,11,16,21: Market trends
# Hour 2,7,12,17,22: Distribution
# Hour 3,8,13,18,23: Technical
# Hour 4,9,14,19: Business models

HOUR_MOD=$((10#$HOUR % 5))

case $HOUR_MOD in
    0)
        TOPIC="competitors"
        QUERIES=(
            "AI agent platforms funding 2026"
            "Character.AI competitors new features"
            "OpenClaw alternatives agent networking"
        )
        ;;
    1)
        TOPIC="market-trends"
        QUERIES=(
            "AI agent market size growth 2026"
            "autonomous AI agents enterprise adoption"
            "multi-agent systems trends"
        )
        ;;
    2)
        TOPIC="distribution"
        QUERIES=(
            "viral growth strategies developer tools"
            "AI product launch case studies 2026"
            "developer community building strategies"
        )
        ;;
    3)
        TOPIC="technical"
        QUERIES=(
            "AI agent authentication standards OAuth"
            "MCP protocol adoption 2026"
            "agent-to-agent communication protocols"
        )
        ;;
    4)
        TOPIC="business-models"
        QUERIES=(
            "AI agent monetization strategies"
            "API-first business models"
            "marketplace commission rates 2026"
        )
        ;;
esac

OUTPUT_FILE="$RESEARCH_DIR/${DATE}-exa-${TOPIC}-${TIMESTAMP}.md"

echo "# Exa Research: ${TOPIC}" > $OUTPUT_FILE
echo "**Date:** ${DATE}" >> $OUTPUT_FILE
echo "**Time:** $(date -u '+%H:%M UTC')" >> $OUTPUT_FILE
echo "**Topic:** ${TOPIC}" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "## Queries Run" >> $OUTPUT_FILE
for query in "${QUERIES[@]}"; do
    echo "- ${query}" >> $OUTPUT_FILE
done
echo "" >> $OUTPUT_FILE

echo "## Findings" >> $OUTPUT_FILE
echo "*[To be filled with mcporter Exa results]*" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "## Implications for LinkClaws" >> $OUTPUT_FILE
echo "*[Analysis of findings]*" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "## Action Items" >> $OUTPUT_FILE
echo "- [ ] Review findings" >> $OUTPUT_FILE
echo "- [ ] Update relevant docs" >> $OUTPUT_FILE
echo "- [ ] Identify opportunities" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "---" >> $OUTPUT_FILE
echo "*Auto-generated by exa-research.sh*" >> $OUTPUT_FILE

echo "Research file created: $OUTPUT_FILE"
echo "Topic: $TOPIC"
echo "Queries: ${#QUERIES[@]}"

# Log to heartbeat state
echo "{\"lastExaResearch\": \"${TIMESTAMP}\", \"topic\": \"${TOPIC}\"}" > /home/ubuntu/clawd/memory/heartbeat-state.json
